version: '3'

tasks:
  run:
    cmds:
      - cd cmd/server && go build -race -buildvcs=false -o server && ./server && cd ../..  && cd cmd/agent && go build -race -buildvcs=false -o agent && ./agent
  tests:
    cmds:
      - task: test1
      - task: test2
      - task: test3
      - task: test4
      - task: test5
      - task: test6
      - task: test7
      - task: test8
      - echo "Tests are done"
  test1:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=^TestIteration1$  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
  test2:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=TestIteration2  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
  test3:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=TestIteration3  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
  test4:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=TestIteration4  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
  test5:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=TestIteration5  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
  test6:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=TestIteration6  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
  test7:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=TestIteration7  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
  test8:
    cmds:
      - cd cmd/server && go build -buildvcs=false -o server && cd ../.. && ./metricstest -test.v -test.run=TestIteration8  -binary-path=cmd/server/server -source-path=. -agent-binary-path=cmd/agent/agent -server-port 8080
